name: "godot-ci export"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:mono-4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.mono.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.mono.stable
      - name: Godot Editor Run
        run: |
          cd $PROJECT_PATH
          dotnet build
          godot --headless -e --quit
          git restore .
          godot --headless -e --quit
      - name: Windows Build
        run: |
          mkdir -v -p build/release-win
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RCA-win
          path: build/release-win

  export-linux:
    name: Linux Export
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:mono-4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.mono.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.mono.stable
      - name: Godot Editor Run
        run: |
          cd $PROJECT_PATH
          dotnet build
          godot --headless -e --quit
          git restore .
          godot --headless -e --quit
      - name: Linux Build
        run: |
          mkdir -v -p build/release-linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RCA-linux
          path: build/release-linux

  release:
    needs: [ export-linux,export-windows ]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Downoad artifact RCA-win
        uses: actions/download-artifact@v4
        with:
          name: RCA-win
          path: artifacts/
      - name: Downoad artifact RCA-linux
        uses: actions/download-artifact@v4
        with:
          name: RCA-linux
          path: artifacts/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "Release ${{ github.event.inputs.release_tag }}"
          body: ""
          files: |
            artifacts/*
          draft: true
          prerelease: false
      
